version: "3.8"
services:
  database:
    # Runs a local SQL Server 2017 instance to store data
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: badgemeup-database
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=BadgeMeUp1!
    volumes:
      - badgemeup-mssqlsystem:/var/opt/mssql
      - badgemeup-mssqluser:/var/opt/sqlserver
  storage:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: badgemeup-storage
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    volumes:
      - badgemeup-storage:/data
  webapp:
    image: badgemeup
    container_name: badgemeup-webapp
    depends_on:
      - database
      - storage
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - BUILDPROFILE=Debug
    ports:
      - "9000:80"
    environment:
      - CONNECTIONSTRINGS__BADGEDB=Data Source=badgemeup-database;Initial Catalog=badges1;User Id=sa;Password=BadgeMeUp1!;Application Name=badgemeup
      - CONNECTIONSTRINGS__badgeImageStorage=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://badgemeup-storage:10000/devstoreaccount1;QueueEndpoint=http://badgemeup-storage:10001/devstoreaccount1;
      - ASPNETCORE_ENVIRONMENT=Development
      - LOGGING__LOGLEVEL__DEFAULT=Information
      - DETAILEDERRORS=true
volumes:
  badgemeup-mssqlsystem:
  badgemeup-mssqluser:
  badgemeup-storage:
